- name: Ensure br_netfilter is enabled.
  modprobe:
    name: br_netfilter
    state: present

- name: Setup bridge nf iptables call
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1
    state: present

- name: Setup bridge nf iptables call for ipv6
  sysctl:
     name: net.bridge.bridge-nf-call-ip6tables
     value: 1
     state: present

- name: Add docker apt key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Apt cache policy
  command: apt-cache policy docker-ce

- name: apt cache update
  apt:
    update_cache: yes

- name: Install Docker prerequisites
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

# TODO: docker-ce 18 is installed by default somehow. Should try to fix this.
- name: Install Docker
  apt:
    name: docker-ce
    state: present

- name: add nvidia docker apt key
  apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey
    state: present

- name: add nvidia docker apt repository
  get_url:
    url: "https://nvidia.github.io/nvidia-docker/ubuntu20.04/nvidia-docker.list"
    dest: /etc/apt/sources.list.d/nvidia-docker.list
  notify: remove nvidia docker apt repository

- name: install nvidia-docker2
  apt:
    name: nvidia-docker2
    state: present
    update_cache: true

- name: Create docker.d folder
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: "u=rwx,g=rx,o=rx"

- name: Add drop-in file for Docker daemon to fix cgroup drivers
  copy:
    src: "docker.conf"
    dest: "/etc/systemd/system/docker.service.d/docker.conf"

- name: Set default runtime to nvidia-docker
  lineinfile:
    path: /etc/docker/daemon.json
    line: "    \"default-runtime\": \"nvidia\","
    insertbefore: "\"runtimes\": {"

- name: Restart the Docker daemon
  systemd:
    name: docker
    enabled: yes
    state: restarted
