- name: Create group for user {{ user.name }}
  group:
    name: "{{ user.name }}"
    state: present

- name: Create user {{ user.name }}
  user:
    name: "{{ user.name }}"
    comment: "{{ user.comment }}"
    groups: "{{ user.groups }}"
    password: "{{ user.password }}"
    generate_ssh_key: yes
    ssh_key_type: ed25519
    update_password: on_create
    state: present

- name: Grab user's public key
  slurp:
    src: "/home/{{ user.name }}/.ssh/id_ed25519.pub"
  register: user_key

- name: Add user's SSH key to authorized_keys
  authorized_key:
    user: "{{ user.name }}"
    state: present
    key: "{{ user_key['content'] | b64decode }}"

- name: Set permissions for SSH folder and files correctly
  file:
    path: "/home/{{ user.name }}/.ssh"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: u=rwX,g=,o=
    recurse: yes

- name: Setup openvpn CSR config
  template:
    src: "vpn_csr.conf.j2"
    dest: "/home/{{ user.name }}/vpn_csr.conf"

- name: Setup kubectl CSR config
  template:
    src: "kubectl_csr.conf.j2"
    dest: "/home/{{ user.name }}/kubectl_csr.conf"

- name: Genereate VPN client CSR
  command: >
    "openssl req -new -newkey rsa:4096 -keyout /home/{{ user.name }}/openvpn.key"
    "-out /home/{{ user.name }}/openvpn.csr -config /home/{{ user.name }}/vpn_csr.conf"

- name: Sign CPN client CSR
  command: "openssl ca -config {{ ca.path }}/ca.conf -notext -in /home/{{ user.name }}/openvpn.csr -out /home/{{ user.name }}/openvpn.crt"

- name: Backup openvpn certificate
  copy:
    src: "/home/{{ user.name }}/openvpn.crt"
    dest: "{{ ca.path }}/openvpn_certs/{{ user.name }}.crt"
    remote_src: yes

- name: Generate Kubectl client CSR
  command: >
    "openssl req -new -newkey rsa:4096 -keyout /home/{{ user.name }}/kubectl.key"
    "-out /home/{{ user.name }}/kubectl.csr -config /home/{{ user.name }}/kubectl_csr.conf"

- name: Sign CPN Kubectl CSR
  command: "openssl ca -config {{ ca.path }}/ca.conf -notext -in /home/{{ user.name }}/kubectl.csr -out /home/{{ user.name }}/kubectl.crt"

- name: Backup kubectl certificate
  copy:
    src: "/home/{{ user.name }}/kubectl.crt"
    dest: "{{ ca.path }}/kubectl_certs/{{ user.name }}.crt"
    remote_src: yes