- name: Restart sshd
  service:
    name: sshd
    state: restarted

- name: Restart iptables
  service:
    name: iptables
    state: restarted

- name: Stop firewalld
  service:
    name: firewalld
    state: stopped