- name: Update apt-get repo and cache
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: Upgrade all apt packages
  apt:
    upgrade: dist
    force_apt_get: yes

- name: Check if a reboot is needed for Debian and Ubuntu boxes
  register: reboot_required_file
  stat:
    path: /var/run/reboot-required
    get_md5: no

- name: Reboot required
  debug:
    msg: "Reboot required due to kernel updates"
  when: reboot_required_file.stat.exists
