kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: administrators-binding
subjects:
  - kind: Group
    name: administrators
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: administrators
  apiGroup: rbac.authorization.k8s.io
