apiVersion: v1
kind: LimitRange
metadata:
  name: limit-resources
spec:
  limits:
    - default:
        memory: 512Mi
        cpu: 1
      defaultRequest:
        memory: 512Mi
        cpu: 1
      type: Container
