---
# Requires EPEL-release repo
- name: Install OpenVPN
  yum:
    name: openvpn-2.4.4
    state: present

- name: Write OpenVPN config file
  template:
    src: openvpn.conf.j2
    dest: /etc/openvpn/server/openvpn.conf
    owner: root
    group: root
    mode: 700

- name: Write DHParam file
  template:
    # This is not a secret, so it may be stored in a template.
    src: "dh2048.pem"
    dest: "/etc/openvpn/server/{{ vpn.dh_parameter_filename }}"

- name: Check if openvpn server certificate exists
  stat:
    path: "/etc/openvpn/server/{{ vpn_server.cert_filename }}"
  register: openvpn_server_cert

- block:
  - name: Setup VPN server CSR config
    template:
      src: "openvpn_server_csr.conf.j2"
      dest: "/etc/openvpn/server/openvpn_server_csr.conf"

  - name: Generate VPN server CSR
    command: >
      openssl req -new -newkey rsa:4096 -nodes
      -keyout /etc/openvpn/server/{{ vpn.server_private_key_filename }}
      -out /etc/openvpn/server/openvpn.csr
      -config /etc/openvpn/server/openvpn_server_csr.conf

  - name: Sign VPN server CSR
    command: >
      openssl ca -batch -config {{ ca.path }}/ca.conf -notext
      -in /etc/openvpn/server/openvpn.csr
      -out /etc/openvpn/server/{{ vpn.server_cert_filename }}

  - name: Write OpenVPN server cert
    copy:
      content: "{{ vpn_server.cert }}"
      dest: "/etc/openvpn/server/{{ vpn_server.cert_filename }}"
  when: openvpn_server_cert.stat.exists == False

# TODO
- name: Write TA key
  copy:
    content: "{{ vpn_server.ta_key }}"
    dest: "/etc/openvpn/server/{{ vpn_server.ta_key_filename }}"

- notify: Restart OpenVPN

# TODO: log rotate log files?
