apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  # Make API server listen on VPN IP
  advertiseAddress: {{ vpn.hyperion_ip }}
apiServerExtraArgs:
  # Enable audit log
  audit-policy-file: /etc/kubernetes/pki/audit-conf.yml
