apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
api:
  # Make API server listen on VPN IP
  advertiseAddress: {{ vpn.hyperion_ip }}
apiServerExtraArgs:
  # Enable audit log
  audit-policy-file: /etc/kubernetes/pki/audit-conf.yml
  feature-gates: "DevicePlugins=true,PodPriority=true"
  admission-control: "NamespaceLifecycle,LimitRanger,ServiceAccount,PersistentVolumeLabel,DefaultStorageClass,DefaultTolerationSeconds,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota,Priority"
  runtime-config: "scheduling.k8s.io/v1alpha1=true"
controllerManagerExtraArgs:
  feature-gates: "DevicePlugins=true,PodPriority=true"
schedulerExtraArgs:
  feature-gates: "DevicePlugins=true,PodPriority=true"
