- name: Disallow SSH password authentication
  lineinfile: dest=/etc/ssh/sshd_config
              regexp="^PasswordAuthentication"
              line="PasswordAuthentication no"
              state=present
  notify: Restart sshd

# CentOS uses firewalld by default. We use Iptables
# because we're more familiar with that tool.
- name: Install IPTables
  yum:
    name: iptables-services-1.4.21

- name: Enable IPTables service
  systemd:
    name: iptables
    enabled: yes
    state: started

- name: Stop firewalld
  service:
    name: firewalld
    state: stopped

- name: Allow established incoming connections
  iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT

- name: Allow all incoming traffic from loopback device
  iptables:
    chain: INPUT
    in_interface: lo
    jump: ACCEPT

- name: Allow VPN traffic from WAN
  iptables:
    chain: INPUT
    protocol: "{{ vpn.protocol }}"
    destination_port: "{{ vpn.port }}"
    jump: ACCEPT

- name: Allow SSH, HTTPS and kubectl traffic from VPN subnet
  iptables:
    chain: INPUT
    protocol: tcp
    source: "{{ vpn.subnet }}/255.255.255.0"
    destination_port: "{{ item }}"
    jump: ACCEPT
  with_items:
    - 22
    - 443
    - 6443

- name: Allow pods to access API server in Kubernetes
  iptables:
    chain: INPUT
    protocol: tcp
    destination: "{{ vpn.hyperion_ip }}" # this is the IP the API server listens on
    in_interface: weave
    destination_port: 6443
    jump: ACCEPT

- name: Allow port range for LAN
  iptables:
    chain: INPUT
    protocol: tcp
    source: "{{ bdr_lan.subnet }}/255.255.255.0"
    destination_port: "8000:9000"
    jump: ACCEPT

- name: Block all incoming traffic
  iptables:
    chain: INPUT
    policy: DROP

- name: Reboot persist IPtables rule changes
  command: /usr/libexec/iptables/iptables.init save
