---
- hosts: gpu
  become: yes
  roles:
    - repositories
    - update
    - essentials
    - ca
    - vpn
    - security
    - nvidia-drivers
    - docker
    - kubernetes
    - groups_and_users
