---
- hosts: gpu
  become: yes
  roles:
    - update
    - essentials
    - ca
    - vpn
    - nvidia-drivers
    - docker
    - microk8s
    - kubernetes
    - cron
    - docker-registry
    - mdns
    - groups_and_users
    - apcupsd
    - security
