---
- hosts: gpu
  become: yes
  vars_files:
    - vars.yml
  roles:
    - repositories
    - update
    - essentials
    - security
    - groups_and_users
    - nvidia-drivers
    - docker
    - kubernetes
