---
- hosts: gpu
  become: yes
  roles:
    #- repositories
    #- update
    #- essentials
    #- ca
    #- vpn
    #- nvidia-drivers
    #- docker
    #- kubernetes
    #- cron
    - groups_and_users
    - security