kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: {{ user.name }}
  name: {{ user.name }}-role
rules:
  # Add read rights to everything in the user's namespace
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "watch", "list", "describe"]
  # Add write rights to jobs
  - apiGroups: ["batch", "extensions"]
    resources: ["jobs"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete", "describe"]
