kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ user.name }}-cluster-binding
subjects:
  - kind: User
    name: {{ user.name }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: {{ user.name }}-cluster-role
  apiGroup: rbac.authorization.k8s.io
