apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources-{{ user.name }}
  namespace: {{ user.name }}
spec:
  hard:
    pods: 4
    requests.cpu: 4
    requests.memory: 24Gi
    limits.cpu: 4
    limits.memory: 24Gi
