apiVersion: v1
kind: LimitRange
metadata:
  name: limit-resources
  namespace: {{ user.name }}
spec:
  limits:
    - default:
        memory: 512Mi
        cpu: 1
      defaultRequest:
        memory: 512Mi
        cpu: 1
      max:
        memory: 24Gi
        cpu: 2
      type: Container
