kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ user.name }}-kubectl-proxy-binding
  namespace: kube-system
subjects:
  - kind: User
    name: {{ user.name }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: {{ user.name }}-kubectl-proxy-role
  apiGroup: rbac.authorization.k8s.io
