#on:
#  push:
#    branches:
#      - feature/gcp-infra

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v1

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: playground-bart
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform plan
        id: plan
        run: |
          terraform plan \
            -var="client_ovpn=${{ secrets.CLIENT_OVPN }}" \
            -var="client_crt=${{ secrets.CLIENT_CRT }}" \
            -var="client_key=${{ secrets.CLIENT_KEY }}" \
            -var="vpn_ca_crt=${{ secrets.VPN_CA_CRT }}" \
            -out=tfplan

#      - name: Terraform apply
#        run: |
#          terraform apply tfplan
